###Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "tribianijoey5100@gmail.com",
  "name": "Joey",
  "password": "joey123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "customer@shopie.com",
  "password": "customer123"
}

### forgot password
POST  http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "tobymaguire324@gmail.com"
}

# {
#   "email": "johndoe@gmail.com"
# }


### reset password
POST  http://localhost:3000/auth/reset-password/dce5911e927f83d41a8ec54ed356f31bbf55a33d4a20bb6f21b29dd64d321d44
Content-Type: application/json

{
  "newPassword": "toby22"
}

# {
#   "newPassword": "doe123!"
# }
