###CREATE a user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John doe",
    "email": "johndoe@gmail.com",
    "password": "john123"
}

### GET all users
GET  http://localhost:3000/users